### ISSUE TITLE
Underlying WebSocket errors not firing on BinaryClient object

### ISSUE THREAD

**Issue by bradisbell** [binaryjs/binaryjs#67]
The documentation for both BinaryClient and BinaryStream lists `error` as an event:

> Event: 'error'
> 
> function (error) { }
> 
> If the client emits an error, this event is emitted (errors from the underlying net.Socket are forwarded here).

If in the browser (Google Chrome) I do something like this:

```
var binaryClient = new BinaryClient('ws://' + host + '/binary-endpoint');
binaryClient.on('error', function (err) {
    console.log(err);
}
```

... and then kill my Node.js server with `Ctrl + C`, the event handler is never fired, and an unhandled error is written to the console.

If I attach an error handler to a stream though, the error event is fired.

```
binaryClient.on('stream', function (stream, meta) {
    stream.on('error', function (err) {
        console.log(err);
    }
});
```

Is this simply a documentation error?  Or a bug?  Or are both handlers needed, but for different types of errors?

**Comment by ToniNgethe** [comment]
i keep getting this error. Tried handling it but it keeps crashing my nodejs app.

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

any help?
